/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendaNoLinkRouteImport } from './routes/venda-no-link'
import { Route as UpFotosRouteImport } from './routes/up-fotos'
import { Route as TrinityTecnologiasRouteImport } from './routes/trinity-tecnologias'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as ProcessoRouteImport } from './routes/processo'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MidiaOoh360RouteImport } from './routes/midia-ooh-360'
import { Route as GrupoRouteImport } from './routes/grupo'
import { Route as DiferenciaisRouteImport } from './routes/diferenciais'
import { Route as DepoimentosRouteImport } from './routes/depoimentos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BuskiacheRouteImport } from './routes/buskiache'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as A3hPrintRouteImport } from './routes/a3h-print'
import { Route as IndexRouteImport } from './routes/index'

const VendaNoLinkRoute = VendaNoLinkRouteImport.update({
  id: '/venda-no-link',
  path: '/venda-no-link',
  getParentRoute: () => rootRouteImport,
} as any)
const UpFotosRoute = UpFotosRouteImport.update({
  id: '/up-fotos',
  path: '/up-fotos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrinityTecnologiasRoute = TrinityTecnologiasRouteImport.update({
  id: '/trinity-tecnologias',
  path: '/trinity-tecnologias',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessoRoute = ProcessoRouteImport.update({
  id: '/processo',
  path: '/processo',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MidiaOoh360Route = MidiaOoh360RouteImport.update({
  id: '/midia-ooh-360',
  path: '/midia-ooh-360',
  getParentRoute: () => rootRouteImport,
} as any)
const GrupoRoute = GrupoRouteImport.update({
  id: '/grupo',
  path: '/grupo',
  getParentRoute: () => rootRouteImport,
} as any)
const DiferenciaisRoute = DiferenciaisRouteImport.update({
  id: '/diferenciais',
  path: '/diferenciais',
  getParentRoute: () => rootRouteImport,
} as any)
const DepoimentosRoute = DepoimentosRouteImport.update({
  id: '/depoimentos',
  path: '/depoimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BuskiacheRoute = BuskiacheRouteImport.update({
  id: '/buskiache',
  path: '/buskiache',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const A3hPrintRoute = A3hPrintRouteImport.update({
  id: '/a3h-print',
  path: '/a3h-print',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a3h-print': typeof A3hPrintRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/buskiache': typeof BuskiacheRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/diferenciais': typeof DiferenciaisRoute
  '/grupo': typeof GrupoRoute
  '/midia-ooh-360': typeof MidiaOoh360Route
  '/portfolio': typeof PortfolioRoute
  '/processo': typeof ProcessoRoute
  '/quem-somos': typeof QuemSomosRoute
  '/servicos': typeof ServicosRoute
  '/trinity-tecnologias': typeof TrinityTecnologiasRoute
  '/up-fotos': typeof UpFotosRoute
  '/venda-no-link': typeof VendaNoLinkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a3h-print': typeof A3hPrintRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/buskiache': typeof BuskiacheRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/diferenciais': typeof DiferenciaisRoute
  '/grupo': typeof GrupoRoute
  '/midia-ooh-360': typeof MidiaOoh360Route
  '/portfolio': typeof PortfolioRoute
  '/processo': typeof ProcessoRoute
  '/quem-somos': typeof QuemSomosRoute
  '/servicos': typeof ServicosRoute
  '/trinity-tecnologias': typeof TrinityTecnologiasRoute
  '/up-fotos': typeof UpFotosRoute
  '/venda-no-link': typeof VendaNoLinkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a3h-print': typeof A3hPrintRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/buskiache': typeof BuskiacheRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/diferenciais': typeof DiferenciaisRoute
  '/grupo': typeof GrupoRoute
  '/midia-ooh-360': typeof MidiaOoh360Route
  '/portfolio': typeof PortfolioRoute
  '/processo': typeof ProcessoRoute
  '/quem-somos': typeof QuemSomosRoute
  '/servicos': typeof ServicosRoute
  '/trinity-tecnologias': typeof TrinityTecnologiasRoute
  '/up-fotos': typeof UpFotosRoute
  '/venda-no-link': typeof VendaNoLinkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a3h-print'
    | '/admin'
    | '/auth'
    | '/buskiache'
    | '/contato'
    | '/depoimentos'
    | '/diferenciais'
    | '/grupo'
    | '/midia-ooh-360'
    | '/portfolio'
    | '/processo'
    | '/quem-somos'
    | '/servicos'
    | '/trinity-tecnologias'
    | '/up-fotos'
    | '/venda-no-link'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a3h-print'
    | '/admin'
    | '/auth'
    | '/buskiache'
    | '/contato'
    | '/depoimentos'
    | '/diferenciais'
    | '/grupo'
    | '/midia-ooh-360'
    | '/portfolio'
    | '/processo'
    | '/quem-somos'
    | '/servicos'
    | '/trinity-tecnologias'
    | '/up-fotos'
    | '/venda-no-link'
  id:
    | '__root__'
    | '/'
    | '/a3h-print'
    | '/admin'
    | '/auth'
    | '/buskiache'
    | '/contato'
    | '/depoimentos'
    | '/diferenciais'
    | '/grupo'
    | '/midia-ooh-360'
    | '/portfolio'
    | '/processo'
    | '/quem-somos'
    | '/servicos'
    | '/trinity-tecnologias'
    | '/up-fotos'
    | '/venda-no-link'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  A3hPrintRoute: typeof A3hPrintRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BuskiacheRoute: typeof BuskiacheRoute
  ContatoRoute: typeof ContatoRoute
  DepoimentosRoute: typeof DepoimentosRoute
  DiferenciaisRoute: typeof DiferenciaisRoute
  GrupoRoute: typeof GrupoRoute
  MidiaOoh360Route: typeof MidiaOoh360Route
  PortfolioRoute: typeof PortfolioRoute
  ProcessoRoute: typeof ProcessoRoute
  QuemSomosRoute: typeof QuemSomosRoute
  ServicosRoute: typeof ServicosRoute
  TrinityTecnologiasRoute: typeof TrinityTecnologiasRoute
  UpFotosRoute: typeof UpFotosRoute
  VendaNoLinkRoute: typeof VendaNoLinkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venda-no-link': {
      id: '/venda-no-link'
      path: '/venda-no-link'
      fullPath: '/venda-no-link'
      preLoaderRoute: typeof VendaNoLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/up-fotos': {
      id: '/up-fotos'
      path: '/up-fotos'
      fullPath: '/up-fotos'
      preLoaderRoute: typeof UpFotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trinity-tecnologias': {
      id: '/trinity-tecnologias'
      path: '/trinity-tecnologias'
      fullPath: '/trinity-tecnologias'
      preLoaderRoute: typeof TrinityTecnologiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processo': {
      id: '/processo'
      path: '/processo'
      fullPath: '/processo'
      preLoaderRoute: typeof ProcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midia-ooh-360': {
      id: '/midia-ooh-360'
      path: '/midia-ooh-360'
      fullPath: '/midia-ooh-360'
      preLoaderRoute: typeof MidiaOoh360RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupo': {
      id: '/grupo'
      path: '/grupo'
      fullPath: '/grupo'
      preLoaderRoute: typeof GrupoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diferenciais': {
      id: '/diferenciais'
      path: '/diferenciais'
      fullPath: '/diferenciais'
      preLoaderRoute: typeof DiferenciaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depoimentos': {
      id: '/depoimentos'
      path: '/depoimentos'
      fullPath: '/depoimentos'
      preLoaderRoute: typeof DepoimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buskiache': {
      id: '/buskiache'
      path: '/buskiache'
      fullPath: '/buskiache'
      preLoaderRoute: typeof BuskiacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a3h-print': {
      id: '/a3h-print'
      path: '/a3h-print'
      fullPath: '/a3h-print'
      preLoaderRoute: typeof A3hPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  A3hPrintRoute: A3hPrintRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BuskiacheRoute: BuskiacheRoute,
  ContatoRoute: ContatoRoute,
  DepoimentosRoute: DepoimentosRoute,
  DiferenciaisRoute: DiferenciaisRoute,
  GrupoRoute: GrupoRoute,
  MidiaOoh360Route: MidiaOoh360Route,
  PortfolioRoute: PortfolioRoute,
  ProcessoRoute: ProcessoRoute,
  QuemSomosRoute: QuemSomosRoute,
  ServicosRoute: ServicosRoute,
  TrinityTecnologiasRoute: TrinityTecnologiasRoute,
  UpFotosRoute: UpFotosRoute,
  VendaNoLinkRoute: VendaNoLinkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
